upload allure report as artifact

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -99,12 +99,16 @@ jobs:
 
       - name: Deploy Allure Report to GitHub Pages
         run: |
+          if [ ! -d "./allure-report" ]; then
+            echo "Error: allure-report directory does not exist"
+            exit 1
+          fi
           git config --global user.name 'github-actions'
           git config --global user.email 'github-actions@github.com'
           git fetch
           git switch gh-pages || git checkout --orphan gh-pages
           rm -rf *
-          cp -r ./allure-report/* .
+          cp -a ./allure-report/. .
           touch .nojekyll
           git add .
           git commit -m "Update Allure report"
